### ISSUE TITLE
Issue since CT2.3

### ISSUE THREAD

**Issue by xavgra2** [MicrosoftDocs/sql-docs#2296]
Hi, 
For different labs and workshops based on kubernetes and SQL Server, I was using a few yaml files to deploy a SQLServer AG using the operator, and the CTP2.2 release.
But since a few days, this CTP has expired, and no newer CTP release are working.
All the example file on the github account are limited to CTP2.1 release.

Is there any know issue ? A better place to report this issue ?

Xavier.
They failed with this error : "panic: MSSQL_POD_NAME env var does not have valid value"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7224b0c-9cf8-08e7-684d-a086be0c9022
* Version Independent ID: d91d56e2-363d-0f7a-ad93-cb9af8bd836d
* Content: [Always On availability groups for containers running Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-ag-kubernetes?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/linux/sql-server-ag-kubernetes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-ag-kubernetes.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@MikeRayMSFT This might not be a documentation issue, can you please process this issue #2296.

**Comment by MikeRayMSFT** [comment]
@xavgra2 
Thank you for the submission, and thank you for walking through our pre-release features.
As SQL Server 2019 is in preview, these features and the related instructions are being updated. Look for updates in an upcoming CTP release. 

If you need to try with the current CTP, please make the following changes to the Operator yaml file. 
```yaml
- apiGroups: [mssql.microsoft.com]
  resources: [sqlservers]
  verbs: [get, list, watch,update]
---
        - name: MSSQL_K8S_NAMESPACE
          valueFrom:
            fieldRef: {fieldPath: metadata.namespace}
        - name: MSSQL_POD_NAME
          valueFrom:
            fieldRef: {fieldPath: metadata.name}
```
