### ISSUE TITLE
Adding volume breaks SQL Server container on linux

### ISSUE THREAD

**Issue by piotrek-k** [MicrosoftDocs/sql-docs#4178]
Referring to "Persisting your data" section: Is anyone encountering such problem? I'm trying to run sqlserver container on Linux machine. Using volume to persist database contents outside of container results with some strange errors.

Here is docker-compose output of sqlserver container called `db`:
```
db_1            | SQL Server 2019 will run as non-root by default.
db_1            | This container is running as user mssql.
db_1            | To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
db_1            | 2020-02-19 13:56:21.67 Server      Setup step is copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf'.
2020-02-19 13:56:21.78 Server      ERROERROR: BootstrapSystemDataDirectories() failure (HRESULT 0x80070002)
R: Setup FAILED copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf':  2(The system cannot find the file specified.)
webserver_db_1 exited with code 1
```

Here is my docker-compose:
```
version: '3.4'
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "[some password]"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433 # port for management
    volumes:
      - ./__database__:/var/opt/mssql/data # db data 
```

Database works fine if I comment out 2 last lines (remove "volumes" section).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dc2ec36-4915-f7ab-3104-282acc9321e6
* Version Independent ID: fc98af17-f3c5-adff-69ca-593f985e7882
* Content: [Configuration options for SQL Server on Docker - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sql-server-2017#persist)
* Content Source: [docs/linux/sql-server-linux-configure-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**
