### ISSUE TITLE
mssql k8s example outdated apiVersion?

### ISSUE THREAD

**Issue by agowa338** [MicrosoftDocs/sql-docs#4344]
The example k8s yaml did not work, as the apiversion of the deployment is outdated. And also the SQL Server version selector on the left does not influence the pulled docker container, the example shows 2017-latest even if 2019 is selected. And also the Environment variable for the SA_Password is named incorrectly, according to the dockerhub page of the container it should be SA_PASSWORD instead of MSSQL_SA_PASSWORD

In the example it says:
```
apiVersion: apps/v1beta1
kind: Deployment
```
where as it should be:
```
apiVersion: apps/v1
kind: Deployment
```

**Note**: I did not run this on azure, therefore I don't know if maybe azure uses an older version of k8s. I therefore also had to replaced the persistent volume part.

The full example for non azure:
```
apiVersion: v1
data:
  username: c2EK
  password: TXlDMG05bCZ4UEBzc3cwcmQ=
kind: Secret
metadata:
  name: mssql
type: kubernetes.io/basic-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: password 
        volumeMounts:
        - name: mssql
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql
        hostPath:
          path: /srv/mssql
          type: DirectoryOrCreate
      initContainers:
      - name: install
        image: busybox
        command:
        - chown
        - "10001:10001"
        - "/work-dir"
        volumeMounts:
        - name: mssql
          mountPath: "/work-dir"
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04922c04-a2da-186c-5946-1cc4d9a7447b
* Version Independent ID: 6e490885-cdd7-079a-0b3a-4688616b0954
* Content: [Deploy a SQL Server container with Azure Kubernetes Services (AKS) - SQL Server](https://docs.microsoft.com/en-us/sql/linux/tutorial-sql-server-containers-kubernetes?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/tutorial-sql-server-containers-kubernetes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/tutorial-sql-server-containers-kubernetes.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**
