### ISSUE TITLE
Incorrect links for educational resources

### ISSUE THREAD

**Issue by ryepup** [MicrosoftDocs/sql-docs#4905]
Most of the links in the "Additional Resources" section on https://docs.microsoft.com/en-us/sql/sql-server/educational-sql-resources do not point to the intended sites.

All 5 links point to either `/azure/sql-database/sql-database-managed-instance` or `/azure/sql-database/sql-database-single-database`, and I think they are intended to be links to other sites:

```yaml
  - title: Additional resources 
    linkLists:
    - linkListType: reference 
      links:
      - text: Microsoft Learn
        url: /azure/sql-database/sql-database-single-database
      - text: LinkedIn Learning
        url: /azure/sql-database/sql-database-managed-instance
      - text: Microsoft Virtual Academy
        url: /azure/sql-database/sql-database-single-database
      - text: Pluralsight
        url: /azure/sql-database/sql-database-managed-instance
      - text: Channel 9
        url: /azure/sql-database/sql-database-managed-instance
```

This block starts at https://github.com/MicrosoftDocs/sql-docs/blob/6593b3b6365283bb76c31102743cdccc175622fe/docs/sql-server/educational-sql-resources.yml#L128
