### ISSUE TITLE
apiVersion of the Azure SQL K8s Deployment 

### ISSUE THREAD

**Issue by kasunsjc** [MicrosoftDocs/sql-docs#4961]
[Enter feedback here]

**apiVersion** of the deployment has to be changed 

In documentation - apps/v1beta1
with new Kubernetes - apps/v1

correct Yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04922c04-a2da-186c-5946-1cc4d9a7447b
* Version Independent ID: 6e490885-cdd7-079a-0b3a-4688616b0954
* Content: [Deploy a SQL Server container with Azure Kubernetes Services (AKS) - SQL Server](https://docs.microsoft.com/en-us/sql/linux/tutorial-sql-server-containers-kubernetes?view=sql-server-ver15&source=docs)
* Content Source: [docs/linux/tutorial-sql-server-containers-kubernetes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/tutorial-sql-server-containers-kubernetes.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@kasunsjc -- Kasun, thank you for your feedback.  I am looking into this article.

**Comment by kasunsjc** [comment]
sorry I forget to add another correction 

with apps/v1 you need to add following to selector to the deployment to match the pods labels 
```
selector:
    matchLabels:
      app: mssql
```
Following is the complete YAML 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer

```
