### ISSUE TITLE
Mapping /var/opt/mssql/data directory on Docker for Windows fails

### ISSUE THREAD

**Issue by petermicuch** [MicrosoftDocs/sql-docs#5314]
In the article it is written that "Host volume mapping for Docker on Windows does not currently support mapping the complete /var/opt/mssql directory. However, you can map a subdirectory, such as /var/opt/mssql/data to your host machine."

I have only configured /var/opt/mssql/data directory to be persisted in the Docker host, but I am still getting error on the startup. I even tried to persist log and secrets directory together with data, but still the same problem. So this comment is misleading. Permission wise it should be fine as I am using init container to set correct permissions: command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql/data"]

2020-08-10 13:34:27.15 Server      Error 87(The parameter is incorrect.) occurred while opening file '/var/opt/mssql/data/master.mdf' to obtain configuration information at startup. An invalid startup option might have caused the error. Verify your startup options, and correct or remove them if necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dc2ec36-4915-f7ab-3104-282acc9321e6
* Version Independent ID: fc98af17-f3c5-adff-69ca-593f985e7882
* Content: [Configuration options for SQL Server on Docker - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sql-server-ver15#mount-a-host-directory-as-data-volume)
* Content Source: [docs/linux/sql-server-linux-configure-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by petermicuch** [comment]
I was a bit more specific about my use-case [here](<https://github.com/Microsoft/mssql-docker/issues/136#issuecomment-671382769>)

**Comment by WilliamAntonRohm** [comment]
@petermicuch -- thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

@vin-yu -- please look into this issue.

**Comment by petermicuch** [comment]
I did some experimenting today and here is what I found:

I have noticed that Docker Desktop for Windows by default pushes all volumes into `/var/lib/k8s-pvs/` on the linux VM. So I set path in my volume to `/var/lib/k8s-pvs/virtual-clinic-mssql/data` instead of `/opt/virtual-clinic-mssql/data` and the template from my previous post worked fine. There is no error anymore.

I also tried with `/var/lib/virtual-clinic-mssql/data` and it worked. I tried several other directories outside of /var/lib (e.g. /tmp or /opt), but without success. This seems like some kind of permission issues. Here is the output of the directory on the host, when all runs fine:
```
/var/lib/virtual-clinic-mssql/data # ls -all
total 129420
drwxr-xr-x 2 10001 root     4096 Aug 11 10:40 .
drwxr-xr-x 3 root  root     4096 Aug 11 10:40 ..
-rw-r----- 1 10001 root      256 Aug 11 10:40 Entropy.bin
-rw-r----- 1 10001 root  4194304 Aug 11 10:40 master.mdf
-rw-r----- 1 10001 root  2097152 Aug 11 10:40 mastlog.ldf
-rw-r----- 1 10001 root  8388608 Aug 11 10:40 model.mdf
-rw-r----- 1 10001 root 14090240 Aug 11 10:40 model_msdbdata.mdf
-rw-r----- 1 10001 root   524288 Aug 11 10:40 model_msdblog.ldf
-rw-r----- 1 10001 root   524288 Aug 11 10:40 model_replicatedmaster.ldf
-rw-r----- 1 10001 root  4194304 Aug 11 10:40 model_replicatedmaster.mdf
-rw-r----- 1 10001 root  8388608 Aug 11 10:40 modellog.ldf
-rw-r----- 1 10001 root 14090240 Aug 11 10:40 msdbdata.mdf
-rw-r----- 1 10001 root   524288 Aug 11 10:40 msdblog.ldf
-rw-r----- 1 10001 root  8388608 Aug 11 10:40 tempdb.mdf
-rw-r----- 1 10001 root  8388608 Aug 11 10:40 tempdb2.ndf
-rw-r----- 1 10001 root  8388608 Aug 11 10:40 tempdb3.ndf
-rw-r----- 1 10001 root  8388608 Aug 11 10:40 tempdb4.ndf
-rw-r----- 1 10001 root  8388608 Aug 11 10:40 tempdb5.ndf
-rw-r----- 1 10001 root  8388608 Aug 11 10:40 tempdb6.ndf
-rw-r----- 1 10001 root  8388608 Aug 11 10:40 tempdb7.ndf
-rw-r----- 1 10001 root  8388608 Aug 11 10:40 tempdb8.ndf
-rw-r----- 1 10001 root  8388608 Aug 11 10:40 templog.ldf
```
And here when it fails:
```
/opt/virtual-clinic-mssql/data # ls -all
total 54144
drwxr-xr-x 2 10001 root      240 Aug 11 10:38 .
drwxr-xr-x 3 root  root       60 Aug 11 10:38 ..
-rw-r----- 1 10001 root  4194304 Aug 11 10:38 master.mdf
-rw-r----- 1 10001 root   524288 Aug 11 10:38 mastlog.ldf
-rw-r----- 1 10001 root  8388608 Aug 11 10:38 model.mdf
-rw-r----- 1 10001 root 14090240 Aug 11 10:39 model_msdbdata.mdf
-rw-r----- 1 10001 root   524288 Aug 11 10:39 model_msdblog.ldf
-rw-r----- 1 10001 root   524288 Aug 11 10:39 model_replicatedmaster.ldf
-rw-r----- 1 10001 root  4194304 Aug 11 10:39 model_replicatedmaster.mdf
-rw-r----- 1 10001 root  8388608 Aug 11 10:38 modellog.ldf
-rw-r----- 1 10001 root 14090240 Aug 11 10:38 msdbdata.mdf
-rw-r----- 1 10001 root   524288 Aug 11 10:38 msdblog.ldf
```

Do you have some logs where one could find what exactly it the problem? I have for example Oracle DB setup exactly the same way as mssql and there it works fine even when hostpath is set to `/opt/oracle-data`. So I wonder why this is an issue in case of mssql.

Is this thread a good place to address this issue at all?

**Comment by petermicuch** [comment]
I forgot to mention, that it also works when I map entire `mssql` directory and not just `data` subdirectory as described in the referenced article.

I.e. this works:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql-database
  namespace: default
  labels:
    app: mssql
    track: canary
spec:
  serviceName: mssql-database-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mssql
      role: master
  template:
    metadata:
      name: mssql-database
      labels:
        app: mssql
        track: canary
        role: master
    spec:
      containers:
      - name: mssql-database
        image: mcr.microsoft.com/mssql/server:2019-latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ACCEPT_EULA
          value: "Y"   
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-db-secret
              key: password
        - name: MSSQL_PID
          value: Developer
        ports:
        - name: mssqlport
          containerPort: 1433
        volumeMounts:
        - name: mssql-database-data
          mountPath: /var/opt/mssql
      initContainers:
      - name: mssql-change-owner
        image: busybox:latest
        command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql"]
        volumeMounts:
        - name: mssql-database-data
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-database-data
        hostPath:
          path: /var/lib/virtual-clinic-mssql
          type: DirectoryOrCreate
```
