### ISSUE TITLE
 Unable to locate package msodbcsql17

### ISSUE THREAD

**Issue by ravisharmaa** [MicrosoftDocs/sql-docs#6789]
I am having problems while doing the docker-compose build. My machine

Platform: Mac OS Big Sur M1 2020, Rosetta Installed.
Docker desktop version Version 4.0.0 (4.0.0.12)

Docker File 

```
 ARG PHP_VERSION="7.4-fpm"

FROM php:${PHP_VERSION}

ARG NODE_VERSION=15
ARG IMAGICK=false
ARG MSSQL=true
ARG MYSQLI=false

USER root

ENV ACCEPT_EULA=Y

# Install system dependencies
RUN apt-get update > /dev/null && \
    apt-get install -y --no-install-recommends \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    zip \
    unzip \
    libmagickwand-dev \
    libxslt1-dev \
    xfonts-75dpi \
    xfonts-base \
    > /dev/null

# Microsoft SQL Server Prerequisites
RUN if [ "$MSSQL" = "true" ]; then \
    apt-get update > /dev/null \
    && apt-get install -y --no-install-recommends gnupg2 > /dev/null \
    && apt-get update > /dev/null \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/9/prod.list \
        > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get install -y --no-install-recommends \
        locales \
        apt-transport-https \
        > /dev/null \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen > /dev/null \
    && apt-get update > /dev/null \
    && apt-get -y --no-install-recommends install \
        unixodbc-dev \
        msodbcsql17 \
        > /dev/null \
    ; fi

# Install Imagick
RUN if [ "$IMAGICK" = "true" ]; then pecl install imagick > /dev/null || echo "^"; fi

# Install PHP extensions
RUN docker-php-ext-install \
    pdo_mysql \
    mbstring \
    exif \
    pcntl \
    bcmath \
    gd \
    soap \
    zip \
    intl \
    xsl \
    calendar \
    > /dev/null

# Install Imagick
RUN if [ "$MYSQLI" = "true" ]; then docker-php-ext-install mysqli > /dev/null || echo "^"; fi

# Set PHP ini vars

# Install & enable Microsoft SQL Server
RUN if [ "$MSSQL" = "true" ]; then \
    docker-php-ext-install pdo pdo_mysql > /dev/null \
    && pecl install sqlsrv pdo_sqlsrv > /dev/null \
    && docker-php-ext-enable sqlsrv pdo_sqlsrv > /dev/null \
    ; fi

# Enable Imagick
RUN if [ "$IMAGICK" = "true" ]; then docker-php-ext-enable imagick > /dev/null ; fi

# Get latest Composer
RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer > /dev/null

# Install Node.js
RUN curl --silent --location https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - > /dev/null
RUN apt-get install --yes nodejs build-essential > /dev/null \
    && npm install -g @vue/cli > /dev/null
RUN mkdir /tmp/npm && \
    npm set cache --global /tmp/npm && \
    chmod -R 777 /tmp/npm

RUN chmod -R 777 /home

# Clear cache
RUN apt-get clean > /dev/null && \
    rm -rf /var/lib/apt/lists/*


# Set working directory
WORKDIR /var/www

# Copy application folder
COPY . /var/www

# Copy existing permissions from folder to docker
#COPY --chown=www:www . /var/www
#RUN chown -R www-data:www-data /var/www



EXPOSE 9000
CMD ["php-fpm"]

```

And the docker compose

```
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www

    volumes:
    - ./:/var/www
    - ./php/upload.ini:/etc/php/conf.d/upload.ini


  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
    - "8080:80"
    - "8143:443"

    volumes:
    - ./:/var/www
    - ./nginx/conf.d/:/etc/nginx/conf.d

  varnish:
    build:
      context: .
      dockerfile: ./varnish/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - webserver
    links:
      - webserver
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    restart: unless-stopped
    tty: true


```
